### ISSUE TITLE
How to avoid the "Other" Category?

### ISSUE THREAD

**Issue by grzchr15** [sgiehl/piwik-plugin-IPReports#20]
Matomo records Ipv4 and Ipv6 addresses.
But i see lots of "other"

IIPv4 / IPv6 usage
IP-ADDRESS	VISITS
IPv4	 33.7%29,451
IPv6	 0.4%311
Others ([learn more](https://matomo.org/faq/how-to/faq_54/))	 65.9%57,505

Whats is counted as "other". faq_54 seems not a answer to this question

**Comment by sgiehl** [comment]
There actually shouldn't be any "others" in that report. At least it was not intended to have one.
I need to check where that comes from...

**Comment by sgiehl** [comment]
This should be fixed now. I've also published a new release.
Unfortunately this won't fix already processed reports. If you need those reports fixed, you may need to invalidate them.
